name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["master"] # or your default branch
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Adjust Ruby version if needed, check Gemfile.lock or project docs
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        working-directory: ./vonge-jekyll-bookshop-template/site # Specify working directory for bundle install
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        # Use a ruby-version step with bundler-cache to install gems automatically.
        # Alternatively, replace this with your own build script.
        run: bundle exec jekyll build --source ./vonge-jekyll-bookshop-template/site --destination ./vonge-jekyll-bookshop-template/site/_site --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository to GitHub Pages, but Jekyll builds to ./_site in the source dir
          path: './vonge-jekyll-bookshop-template/site/_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 