title: Bo
description: Bo is a compassionate AI companion for deeper connection.
social_media_share_image: /images/bo.png
#disqus-identifier: # Add your Disqus identifier
#google-analytics: # Add your GA Tracking Id